sanberhub/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();

Route::get('/', 'HomeController@index')->name('home');;

Route::get('/home', 'HomeController@index')->name('home.alt');

Route::resource('user', 'UserController');

Route::resource('post', 'PostController');

Route::get('/follow/{id}', 'FollowController@following')->name('following');
Route::get('/unfollow/{id}', 'FollowController@unfollow')->name('unfollow');

Route::get('/like/{id}', 'LikeController@liking')->name('liking');
Route::get('/unlike/{id}', 'LikeController@unliking')->name('unliking');

sanberhub/resources/views/adminlte/index.blade.php
@extends('adminlte.master')

@section('title')
 - Home
@endsection

@section('header')
<h1>Welcome {{Auth::user()->name}} !</h1>
@endsection

@section('content')
@if (\Session::has('success'))
    <div class="alert alert-success">
        <ul>
            <li>{!! \Session::get('success') !!}</li>
        </ul>
    </div>
@endif
<div class="container">
    <div class="card w-85">
        <div class="card-body">
            <h5 class="card-title">Hello!</h5>
            <p class="card-text">Apa yang anda ingin buat hari ini?</p>
            <a href="/post/create" class="btn btn-outline-primary mb-3 fas fa-edit">Create Post</a>
        </div>
    </div>
            <div class="row mx-auto pt-2">
                @foreach ($post as $value)
                <div class="col-4 mb-3">
                    <div class="card border-secondary mb-2" style="width: 22rem;padding-top: 2px;">
                        <img class="card-img-top mx-auto d-inline" src="img/{{$value->imageurl}}" alt="{{$value->caption}}" style="padding-top:4px;width: 95%;height: auto;">
                        <div class="card-header"><h5>{{$value->title}}</h5></div>
                            <div class="card-body">
                                <p class="card-text">{{$value->body}}</p>
                                <?php
                                    $if_null = App\PostLike::where('user_id', Auth::id())->where('post_id', $value->id)->first();
                                        if(is_null($if_null)){ ?>
                                            <a href="/like/{{$value->id}}" class="btn btn-light far fa-heart"> Like </a>                                        
                                        <?php }
                                        else { ?>
                                            <a href="/unlike/{{$value->id}}" class="btn btn-light fas fa-heart"> Liked </a>
                                <?php } ?>
                                    <a href="#" class="btn btn-light far fa-comments"> Comments </a>
                                    <a href="post/{{$value->id}}" class="btn btn-light fas fa-eye"> Show </a>
                            </div>
                        </div>
                    </div>
                @endforeach
                </div>           
            </div>
</div> 
@endsection

sanberhub/resources/views/adminlte/master.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>SanberHub @yield('title')</title>

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{asset('adminlte/plugins/fontawesome-free/css/all.min.css')}}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{asset('adminlte/dist/css/adminlte.min.css')}}">
  @yield('addstyle')

</head>
<body class="layout-navbar-fixed layout-fixed hold-transition sidebar-mini" style="height: auto;">
<!-- Site wrapper -->
<div class="wrapper">
  <!-- Navbar -->
  @include('adminlte.partials.navbar')
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="#" class="brand-link">
      <img src="{{asset('adminlte/dist/img/AdminLTELogo.png')}}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">SanberHub</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{{asset('adminlte/dist/img/user2-160x160.jpg')}}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="/user/{{Auth::id()}}" class="d-block">{{ Auth::user()->name }}</a>
        </div>
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
        <div class="input-group" data-widget="sidebar-search">
          <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
          <div class="input-group-append">
            <button class="btn btn-sidebar">
              <i class="fas fa-search fa-fw"></i>
            </button>
          </div>
        </div>
      </div>

      <!-- Sidebar Menu -->
      @include('adminlte.partials.sidebar')
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            @yield('header')
          </div>
          <!-- <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Blank Page</li>
            </ol>
          </div> -->
        </div>
      </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">

    @yield('content')

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <footer class="main-footer text-sm">
    <div class="float-right d-none d-sm-block">
      <b>Version</b> 3.1.0
    </div>
    <strong>Template by <a href="https://adminlte.io">AdminLTE.io</a></strong> All rights reserved.
  </footer>

  <!-- Control Sidebar (For Development purposes)-->
  <!-- Control sidebar content goes here -->
  <!-- <aside class="control-sidebar control-sidebar-dark"> -->
  <!-- </aside> -->
  <!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<!-- jQuery -->
<script src="{{asset('adminlte/plugins/jquery/jquery.min.js')}}"></script>
<!-- Bootstrap 4 -->
<script src="{{asset('adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('adminlte/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{{asset('adminlte/dist/js/demo.js')}}"></script>
<!-- Sweet Alert -->
<script src="{{asset('sweetalert/sweetalert.min.js')}}"></script>
<script src="{{asset('sweetalert/swal.min.js')}}"></script>
@stack('script')
</body>
</html>

sanberhub/resources/views/adminlte/profile.blade.php
    @extends('adminlte.master')

@section('title')
 - Profile {{Auth::user()->name}}
@endsection

@section('header')
<h1>Profile Page</h1>
@endsection

@section('content')

<div class="container">

@if($profiledata == null)
<a href="{{route('user.create')}}" class="btn btn-primary mb-3">Create Profile</a>
@endif



@foreach($profile as $p)
<?php
    $if_null = App\Follow::where('toUserId',$p->user_id)->where('fromUserId',Auth::id())->first();
    
    if(is_null($if_null)){ ?>

        <a href="{{route('following', $p->user_id)}}" class="btn fas fa-heart btn-outline-success mb-3"> Follow </a>

        <?php }
        else { ?>

        <a href="{{route('unfollow', $p->user_id)}}" class="btn btn-outline-success mb-3">Following</a>

        <?php } ?>

@if($p->user_id == Auth::id())
<span style="display: inline;">
    <a href="{{route('user.edit', Auth::id())}}" class="btn fas fa-edit btn-outline-primary mb-3">Edit Profile</a>
    <form action="{{route('user.destroy', Auth::id())}}" method="POST" style="display: inline;">
        @csrf
        @method('DELETE')
        <input type="submit" class="btn btn-outline-danger mb-3" value="Delete Profile">
    </form>
</span>
@endif

<div class="row display-inline">
    <div class="card" style="width: 20%;">
        <div class="card-body">
            <h5 class="card-title"><b>Full name :</b></h5>
            <p class="card-text">{{$p->fullname}}</p>
        </div>
    </div>
    <div class="card" style="width: 20%;">
        <div class="card-body">
            <h5 class="card-title"><b>Date of Birth :</b></h5>
            <p class="card-text">{{$p->dob}}</p>
        </div>
    </div>
    <div class="card" style="width: 60%;">
        <div class="card-body">
            <h5 class="card-title"><b>Biodata :</b></h5>
            <p class="card-text">{{$p->bio}}</p>
        </div>
    </div>
</div>
@endforeach
<h2> {{$userdata->name}} Posts</h2>
<div class="row mx-auto pt-2">
@foreach($profilepost as $pp)
<div class="col-4 mb-3">
    <div class="card border-secondary mb-3" style="width: 22rem;padding-top: 4px;">
        <img class="card-img-top mx-auto" src="/img/{{$pp->imageurl}}" alt="{{$pp->caption}}" style="padding-top:4px;width: 95%;height: auto;">
        <div class="card-header"><b>{{$pp->title}}</b></div>
        <div class="card-body">
            <p class="card-text">{{$pp->body}}</p>
            <a href="#" class="btn btn-light far fa-heart"> Like </a>
            <a href="#" class="btn btn-light far fa-comments"> Comments </a>
            <a href="/post/{{$pp->id}}" class="btn btn-light fas fa-eye"> Show </a>
        </div>
    </div>
</div>
@endforeach
</div>
</div>
@endsection